### ISSUE TITLE
A little support for `CommonJS`

### ISSUE THREAD

**Issue by AtLastDopamine** [astoilkov/p-signal#1]
If it's convenient for you, consider supporting `CommonJS`.

Finally, thank you for the open source.

**Comment by astoilkov** [comment]
Hey,

I like the idea that more people can use my packages. However, keeping my open-source repos ESM only is a decision I've made to lessen the burden of maintenance.

I hope this isn't a deal-breaker for you and you find a way to transpile this package to CommonJS.

I'm closing this.
